### ISSUE TITLE
Query extension doesn't preserve filtered `total` count

### ISSUE THREAD

**Issue by chriscombs** [nodes-vapor/paginator#17]
If you filter a query and then paginate the resulting filtered query, it doesn't use the total count of the filtered query. For example, if I have 30 models and filter out 3 of them, the paginator will return those 3 but the meta object will say there are 30 total. 

A temp workaround is to use filteredQuery.all() because the Sequence extension works fine.

**Comment by chriscombs** [comment]
I'll try to see if I can fix this myself today

**Comment by Casperhr** [comment]
@chriscombs @BrettRToomey Have this bug in Lokalbolig also, could be nice with a fast fix (should be fairly easy)

**Comment by Casperhr** [comment]
Testing this now

**Comment by Casperhr** [comment]
works
