### ISSUE TITLE
Leaf extension crash when empty

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/paginator#21]
https://github.com/nodes-vapor/paginator/blob/master/Sources/Paginator%2BLeaf.swift#L85

count = 0

**Comment by Casperhr** [comment]
I fixed it locally by just making a if count > 1 

Should I make a PR with that? or do you have a better idea? @BrettRToomey

**Comment by Casperhr** [comment]
Also the html/css have an error

![image](https://cloud.githubusercontent.com/assets/1279756/23292599/3c6f05f6-fa61-11e6-8b9a-65daa8c57181.png)

**Comment by steffendsommer** [comment]
Fixed in the Vapor 3 version
