### ISSUE TITLE
count vs limit

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/paginator#3]
You will normal call the count limit?

And it could be very smart to have a upper limit, since its the easists way to slow down a db server. Make a request with limit=1000000000000
@BrettRToomey

**Comment by BrettRToomey** [comment]
Yup! I thought of honouring whatever the url query says for `count`, but use the number the programmer passes as the `max`. So someone couldn't maliciously set `?page=1&count=1000000000000` and freeze the db lol.

What do you think of that solution?

**Comment by Casperhr** [comment]
That would be perfect
