### ISSUE TITLE
#paginator(items) not rendered on website

### ISSUE THREAD

**Issue by leonidas-o** [nodes-vapor/paginator#31]
Paginator version 1.0.1
Vapor version 2.0.5
Bootstrap 4

Also got a `paginator.json` file with `"useBootstrap4": true`
got `try addProvider(PaginatorProvider.self)` in the `Config+Setup.swift`
got `#paginator(items)` inside my `foo.leaf` file, but the page prev/next/ 'page number' block is not rendered on the website at all.
<img width="261" alt="screen shot 2017-06-02 at 18 22 53" src="https://cloud.githubusercontent.com/assets/2997492/26735174/1568b256-47c1-11e7-899b-86e8e2827276.png">

**Comment by steffendsommer** [comment]
I'm not 100p sure, but it could be related to what was highlighted in this PR: https://github.com/nodes-vapor/paginator/pull/32 - the fact, that the Leaf stuff is not respecting the naming scheme coming from Fluent. Thanks for reporting @leonidas-o

**Comment by leonidas-o** [comment]
I saw it afterwards in the `Paginator.swift` that you guys are reading the `let convention = Database.default?.keyNamingConvention ?? .camelCase` that's why i closed the PR again.
In `Paginator+Leaf.swift` for me it looks like you're ignoring the convention and just use snake_case:
```
        guard
            let currentPage = paginator["current_page"]?.int,
            let totalPages = paginator["total_pages"]?.int,
            let links = paginator["links"]?.object
        else {
                return nil
        }
```

**Comment by steffendsommer** [comment]
Yes exactly - we're on it: https://github.com/nodes-vapor/paginator/pull/33

**Comment by leonidas-o** [comment]
One other question. `let convention = Database.default?.keyNamingConvention ?? .camelCase` always resolves to nil, so it is always `.camelCase`here. How can you affect the naming convention?
In my `config/fluent.json` I got "keyNamingConvention": "snake_case" and this is only resolving correct via `let convention = drop.database?.keyNamingConvention`
For me therefore `let convention = Database.default?.keyNamingConvention ?? .camelCase` seems kind of useless.

**Comment by steffendsommer** [comment]
@leonidas-o please have a look at https://github.com/nodes-vapor/paginator/releases/tag/1.0.2 if it fixes your issue. We might need a separate issue for how we fetch the keyNamingConvention.

**Comment by leonidas-o** [comment]
@steffendsommer yes this solves the not rendered issue. Thanks! 
I don't know why you're even fetching the keyNamingConvention, as I said, here it resolves always to camelCase. My fluent.json sets the keyNamingConvention to snake_case. So your "namingConvention" is fully independent from the one of a users db. If you ask me, throw that whole namingConvention fetching out of the code and just hard code one way. Haven't went through the whole code, but don't think that the convention fetching is needed at all.

**Comment by steffendsommer** [comment]
I think it makes sense to support the two key naming conventions which Vapor supports. I created a new issue to address this: https://github.com/nodes-vapor/paginator/issues/35

Closing this as we got your original issue resolved - let me know if you have other issues/questions.
