### ISSUE TITLE
nav (Paginator) li (page-item) anchor no href

### ISSUE THREAD

**Issue by leonidas-o** [nodes-vapor/paginator#39]
Paginator Version 1.1.0

When accessing the page over one of the internal links, there is no `?page=1` in the url, and therefore the li (page-item) anchor of e.g. page 2 has no href. You have to to click the `Next` button which adds `?page=2` to the url and only afterwards it is possible to click on the numbered li (page-item) elements.

As I see, it depends on if there is a query or not in the url even though it is not anything with `?page=`. So e.g. If I have `www.mydomain.com/foo` it will not work, but if I have something like `www.mydomain.com/foo?param=whatever` the li anchor tag get its href and it works like expected.

**Comment by steffendsommer** [comment]
Fixed by https://github.com/nodes-vapor/paginator/releases/tag/1.1.1 and https://github.com/nodes-vapor/paginator/releases/tag/0.5.1
