### ISSUE TITLE
paginator block in leaf to big for mobile screens with more than 10 pages

### ISSUE THREAD

**Issue by leonidas-o** [nodes-vapor/paginator#40]
The paginator navigation block in leaf could show e.g. 7 pages, even though there are 20 or more. 

The idea is, on mobile if you have 20 pages the leaf block gets to big to fit on an mobile screen, especially in portrait mode.  
So for example it could display 7 pages, the current page centered plus the others.
See three examples two if you are on page 13, and the next on 20, so the navigation leaf block could show something like:

<< | 10 | 11 | 12 | **13** | 14 | 15 | 16 | >>

<< | 10 | ... | 12 | **13** | 14 | ... | 20 | >>

<< | 10 | ... | 19 | **20** | 21 | ... | 30 | >>

So with this it would be possible to jump 10 pages per click, or one by one with the next and previous buttons. The `...` fields don't know, they does not have to be even clickable, I would say.

**Comment by steffendsommer** [comment]
https://github.com/nodes-vapor/paginator/pull/58
