### ISSUE TITLE
paginator looses url query if same parameter names for multiple values

### ISSUE THREAD

**Issue by leonidas-o** [nodes-vapor/paginator#41]
If you use a dropdown (multiple selects allowed), your query will become something like:
`...?supplier=foo&supplier=whatever`.
If you now use the paginator in leaf navigation block, it will drop the query.
If you add `&page=2` by hand to your url, it will work, you can go back to page 1 and so on. Just the navigation block in leaf is causing the issue. So I guess it should just be the leaf part.

**Comment by steffendsommer** [comment]
https://github.com/nodes-vapor/paginator/pull/58
