### ISSUE TITLE
Gracefully handle a large number of pages

### ISSUE THREAD

**Issue by steffendsommer** [nodes-vapor/paginator#49]
If the number of pages if very large, the leaf tag that shows the page controls ends up being too big which doesn't look great.

**Comment by rasmusebbesen** [comment]
![screen shot 2017-11-17 at 10 42 07](https://user-images.githubusercontent.com/944158/32940839-2358c666-cb84-11e7-97b2-20dfc404ee7e.png)

This is how it is handled in our older systems

**Comment by steffendsommer** [comment]
https://github.com/nodes-vapor/paginator/pull/58
