### ISSUE TITLE
Array Index Out Of Range

### ISSUE THREAD

**Issue by martinlasek** [nodes-vapor/paginator#57]
Reproduce
```swift
// two elements
var userList ["Link", "Zelda"]
// count is higher than amount of elements
userList.paginate(count: 10, on: req)
```

I would've expect `.paginate(count: 10, on: req)` to handle `count` like an "at max" value.

**Comment by steffendsommer** [comment]
@MartinLasek you were expecting this to do 10 per page right? Actually the `count` parameter is different. It's a way to override the way the Paginator calculates the total number of results. This is a bit of an edge case, but it is needed when doing complex queries on the `QueryBuilder` where calling `.count()` would yield the wrong results.

That said, let's keep this issue to see if we can clarify this by doing readme/API docs. What do you think?
