### ISSUE TITLE
Possible to keep other query params between next pages

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/paginator#7]
There needs to be an options to keep current query params in url

fx  myurl?search=casper
and click next page, the search result should stay

This behaviour should also work for the api meta object next url

Either make as an option or do it default imo

**Comment by BrettRToomey** [comment]
I agree, let's default it until someone provides a counter argument to this behavior.

**Comment by steffendsommer** [comment]
Can this be closed @BrettRToomey ?

**Comment by leonidas-o** [comment]
What happened to this feature/enhancement? Can it make into the next release?

**Comment by steffendsommer** [comment]
@leonidas-o we still need to fix this for the leaf part (in JSON responses it should work). We'll try to prioritize to fix this.

**Comment by leonidas-o** [comment]
@steffendsommer any status info about this bug/enhancement?

**Comment by steffendsommer** [comment]
@leonidas-o Sorry for the late reply - it should be ready one of the following days.

**Comment by leonidas-o** [comment]
@steffendsommer okay nice, thanks.

**Comment by steffendsommer** [comment]
@leonidas-o ready for Vapor 1 here: https://github.com/nodes-vapor/paginator/releases/tag/0.5.0 and the Vapor 2 version is incoming.

**Comment by steffendsommer** [comment]
@leonidas-o ready for Vapor 2 here: https://github.com/nodes-vapor/paginator/releases/tag/1.1.0
