### ISSUE TITLE
How to implement sorting with pagination?

### ISSUE THREAD

**Issue by kimsanov** [nodes-vapor/paginator#78]
By default i get unsorted data from query.

`let paginator: Future<OffsetPaginator<Galaxy>> = Galaxy.query(on: req).paginate(on: req)`

But when I try to do something like this:

`let paginator: Future<OffsetPaginator<Galaxy>> = Galaxy.query(on: req).sort(\.someFiled, .ascending).paginate(on: req)`

 I get error from Vapor

> column \"SomeTable.someField\" must appear in the GROUP BY clause or be used in an aggregate function"

What is correct way to get sorted results with pagination?

**Comment by siemensikkema** [comment]
@kimsanov The easiest way is to disable "only full group by": https://stackoverflow.com/questions/23921117/disable-only-full-group-by

**Comment by LinusGeffarth** [comment]
@siemensikkema sounds more like a workaround than a fix, is it?
